pyOpenSSL is required by ansible playbook
ansible-playbook ~/openshift-ansible/playbooks/byo/config.yml
throws
ImportError: No module named OpenSSL.crypto