Update installation-mirror-repository.adoc
We need to add --insecure=true

If we will not pass this argument then we will get the below error:

```
mirror -a ps.json --from-dir=/home/remveabel/images/mirror file://openshift/release:4.15.10* registry.babbar.ocp.com:8443/ocp4/openshift4  --dir /home/registry-user/images/ 2>&1 | tail -n 5 
error: unable to upload blob sha256:3dbd6d14ab672581a0c504cb478bbdd9cfb59f134661b121af44a0383141ecd0 to registry.babbar.ocp.com:8443/ocp4/openshift4: Get "https://registry.babbar.ocp.com:8443/v2/": tls: failed to verify certificate: x509: certificate signed by unknown authority
error: unable to upload blob sha256:0404bbe384152d3d167082f8a1869226a1119b7ea4faeda24d6586372b08e45b to registry.babbar.ocp.com:8443/ocp4/openshift4: Get "https://registry.babbar.ocp.com:8443/v2/": tls: failed to verify certificate: x509: certificate signed by unknown authority
error: unable to upload blob sha256:172b222acc964dc43a669d25ac3f841afb592da5c6fcff0cad45f64b13b2ce1c to registry.babbar.ocp.com:8443/ocp4/openshift4: Get "https://registry.babbar.ocp.com:8443/v2/": tls: failed to verify certificate: x509: certificate signed by unknown authority
info: Mirroring completed in 0s (0B/s)
error: one or more errors occurred while uploading images
```