Flowcollector config spec.loki.url requires https instead of http
spec.loki.url in flowcollector custom resource uses https protocol and port 8080 is a secured port. The certificates injected here are signed by openshift-service-serving-signer. Same can be validated using below command from the node where loki-gateway pod is scheduled.
$ crictl ps | grep gateway
$ crictl inspect <container-id> | grep -i pid
$ nsenter -t <pid-of-loki-gateway-container> -n openssl s_client -connect localhost:8080

Usage of http causes 404 error in Network Traffic menu:
~~~
Error: Request failed with status code 400
[400] Loki message: Client sent an HTTP request to an HTTPS server.
~~~

Fix: After changing http to https, the network flows can be seen in Network Traffic menu.