"oc export" command missing option.
Original command produce error:
 
[root@master ~]# oc export all --as-template=test1
error: you must provide one or more resources by argument or filename