modules/update-service-mirror-release: Use 'oc image mirror ...' for the release image
We can't use:

  $ oc adm release mirror ...

to split the release image out into LOCAL_RELEASE_IMAGES_REPOSITORY,
because oc does not currently understand mirroring.  So there's no way
to tell it "the referenced images you're looking for are actually in
${LOCAL_REGISTRY}/${TEMP_REPOSITORY}", and it fails with:

  error: unable to connect to quay.io/openshift-release-dev/ocp-v4.0-art-dev: Get "https://quay.io/v2/"...
  error: an error occurred during planning

Instead, send the images from disk directly to the target repositoy
for referenced images, and then use 'oc image mirror' again to copy
the release image over to the release-image repository without
worrying about referenced images.  We still need the release images in
that separate repository to avoid Cincinnati consuming excessive
memory trying to load referenced-image layers as if they were release
images [1,2].

I've also softened some REMOVABLE_MEDIA_PATH wording.  The important
point is that REMOVABLE_MEDIA_PATH points to where the removable media
is mounted for both commands, not that you use the same path string.
For example, maybe you mounted to /mnt/a on your external machine, and
then mounted that media to /mnt/b on your internal machine.  You'd
want to use /mnt/b for REMOVABLE_MEDIA_PATH when mirroring from disk,
not /mnt/a.

[1]: https://github.com/openshift/openshift-docs/pull/29630#issuecomment-807921826
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=1850781