Add upgrading to oc 4.9 as a prereq
Move the channel change earlier in the process and note the rollout delay

The exact error message would be as follows in case we want to use that.

```
$ oc adm upgrade channel eus-4.10
error: the requested channel "eus-4.10" is not one of the available channels (candidate-4.8, candidate-4.9, eus-4.8, fast-4.8, fast-4.9, stable-4.8, stable-4.9), you must pass --allow-explicit-channel to continue
```