Update nw-metallb-configure-secondary-interface.adoc
Updated the correct indentation to apply the example configuration. 

While copying the enable-ip-forward.yaml example from the documentation, YAML was failed to apply due to indentation errors. 

~~~
# oc apply -f enable-ip-forward.yaml 
error: error parsing metallb.yaml: error converting YAML to JSON: yaml: line 15: mapping values are not allowed in this context
~~~