Command "oc sa get-token" is deprecated in RHOCP4
Command "$ oc sa get-token <service_account_name>" is deprecated and throwing error :
~~~
Command "get-token" is deprecated, and will be removed in the future version. Use oc create token instead.
error: could not find a service account token for service account <service_account_name>
~~~
Use command "$ oc create token <service_account_name>" instead to get the token for service account.